{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "gs_with_vs_without_limit",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(count) gs_with_limit\nFROM (\n\tSELECT COUNT(id) count\n\tFROM growth_sessions\n\tWHERE attendee_limit < 1000\n\tGROUP BY attendee_limit\n) data;"
    },
    {
     "rawSql": "SELECT SUM(count) gs_with_no_limit\nFROM (\n\tSELECT COUNT(id) count\n\tFROM growth_sessions\n\tWHERE attendee_limit > 1000\n\tGROUP BY attendee_limit\n) data;"
    }
   ]
  },
  {
   "title": "gs_number_and_attendance_over_time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT time, COUNT(growth_session_id) total_gs, SUM(user_count) total_attendees\nFROM (\n\tSELECT growth_session_id, COUNT(user_id) user_count, CAST(date as datetime) time\n\tFROM growth_session_user gsu\n\tJOIN growth_sessions gs ON gs.id = gsu.growth_session_id\n\tGROUP BY growth_session_id\n) data\nGROUP BY time;"
    }
   ]
  },
  {
   "title": "users_with_biggest_number_of_hosted_growth_sessions",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT gs_count.host_name, total_gs hosted_growth_sessions, count total_number_of_attendees\nFROM (\n\tSELECT u.name host_name, COUNT(growth_session_id) total_gs\n\tFROM growth_session_user gs\n\tJOIN users u ON u.id = gs.user_id\n\tWHERE gs.user_type_id = 1\n\tGROUP BY gs.user_id\n) gs_count\nJOIN\n(\n\tSELECT COUNT(user_id) count, u.name host_name\n\tFROM (\n\t\tSELECT user_id, gsu.growth_session_id, gs_owners.owner_id\n\t\tFROM growth_session_user gsu\n\t\tJOIN (\n\t\t\tSELECT gsu.growth_session_id gs_id, user_id owner_id\n\t\t\tFROM growth_session_user gsu\n\t\t\tWHERE gsu.user_type_id = 1\n\t\t\t) gs_owners \n\t\t\tON gs_owners.gs_id = gsu.growth_session_id\n\t) data\n\tJOIN users u ON u.id = data.owner_id \n\tGROUP BY owner_id\n) user_count ON gs_count.host_name = user_count.host_name\nORDER BY total_gs DESC\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "max_gs_attendees",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  MAX(attendee_count.count)\nFROM\n(\n  SELECT count(user_id) as count\n  FROM growth_session_user\n  GROUP BY growth_session_id\n) as attendee_count\n\n\n"
    }
   ]
  },
  {
   "title": "times_users_participated_in_one_gs_together",
   "type": "table",
   "gridPos": { "h": 15, "w": 14, "x": 5, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT u1.name user_1, COUNT(data.user_id1) times_mobbed_together, u2.name user_2\nFROM (\n\tSELECT gsu1.user_id as user_id1, \n\t\t\tgsu2.user_id as user_id2 \n\tFROM growth_session_user gsu1\n\tJOIN growth_session_user gsu2\n\t\tON gsu1.growth_session_id = gsu2.growth_session_id AND\n\t\t\tgsu1.user_id <> gsu2.user_id) data\nJOIN users u1 ON u1.id = data.user_id1\nJOIN users u2 ON u2.id = data.user_id2\nWHERE STRCMP(u1.name, u2.name) = 1\nGROUP BY data.user_id1, data.user_id2\nORDER BY times_mobbed_together DESC;"
    }
   ]
  },
  {
   "title": "avg_attendees_per_gs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(attendee_count.count)\nFROM\n(\n  SELECT COUNT(user_id) count\n  FROM growth_session_user\n  WHERE growth_session_user.user_type_id = 2\n  GROUP BY growth_session_id\n) attendee_count;"
    }
   ]
  },
  {
   "title": "max_number_of_gs_hosted_in_a_day",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(growth_sessions_count.count)\nFROM\n(\n  SELECT COUNT(id) count\n  FROM growth_sessions\n  GROUP BY growth_sessions.date\n) growth_sessions_count;\n\n\n"
    }
   ]
  },
  {
   "title": "avg_gs_duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n\tAVG(length)\nfrom (\n\tSELECT (TIME_TO_SEC(end_time) - TIME_TO_SEC(start_time))/60 \n\tas length\n\tfrom growth_sessions\n) as gs_length;\n"
    }
   ]
  },
  {
   "title": "avg_number_of_daily_gs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(growth_sessions_count.count)\nFROM\n(\n  SELECT COUNT(id) count\n  FROM growth_sessions\n  GROUP BY growth_sessions.date\n) growth_sessions_count;\n\n\n"
    }
   ]
  },
  {
   "title": "total_gs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) count\nFROM growth_sessions;\n\n\n"
    }
   ]
  },
  {
   "title": "max_public_guests_in_a_gs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(gsu.growth_session_id) as guest_attendee_count \nfrom growth_session_user gsu\njoin users on gsu.user_id = users.id\njoin growth_sessions on gsu.growth_session_id = growth_sessions.id\nwhere gsu.user_type_id = 2\nand growth_sessions.is_public = 1\nand users.is_vehikl_member = 0\ngroup by gsu.growth_session_id\norder by guest_attendee_count DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "total_unique_guests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT github_nickname)\nFROM users\nWHERE is_vehikl_member = 0;"
    }
   ]
  },
  {
   "title": "total_unique_participants",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT github_nickname)\nFROM users;\n"
    }
   ]
  },
  {
   "title": "private_vs_public_growth_sessions",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(is_public) AS \"public\"\nFROM growth_sessions\nWHERE is_public = 1;"
    },
    {
     "rawSql": "SELECT COUNT(is_public) AS \"private\"\nFROM growth_sessions\nWHERE is_public = 0;"
    }
   ]
  },
  {
   "title": "top_users_with_most_attended_gs",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 19, "x": 5, "y": 39 },
   "targets": [
    {
     "rawSql": "SELECT u.name, COUNT(growth_session_id) total_gs \nFROM growth_session_user gs\nJOIN users u ON u.id = gs.user_id\nWHERE gs.user_type_id = 2\nGROUP BY gs.user_id\nORDER BY total_gs DESC\nLIMIT 10;"
    }
   ]
  }
 ]
}